// <auto-generated />
// Generated by HardwareSupportCodeGenerator. Do not edit manually.
using System;
using UnityEngine;

namespace USTL.FaceTracking
{
    [Flags]
    internal enum SupportedHardwares
    {
        None = 0,
        [InspectorName("Meta Quest Pro")]
        MetaQuestPro = 1 << 0,
        [InspectorName("Pico 4 Pro, Pico 4 Enterprise")]
        Pico4ProEnterprise = 1 << 1,
        [InspectorName("HTC VIVE Pro Eye")]
        ViveProEye = 1 << 2,
        [InspectorName("HTC VIVE Facial Tracker")]
        ViveFacialTracker = 1 << 3,
        [InspectorName("HTC VIVE Focus 3 Eye Tracking Add-on")]
        ViveFocus3EyeTrackingAddon = 1 << 4,
        [InspectorName("HTC VIVE Focus 3 Facial Tracker Add-on")]
        ViveFocus3FacialTrackerAddon = 1 << 5,
        [InspectorName("HTC VIVE XR Elite Full Face Tracker")]
        ViveXrEliteFullFaceTracker = 1 << 6,
        [InspectorName("HTC VIVE Focus Vision + Face Tracking Add-on")]
        ViveFocusVisionFaceTrackingAddon = 1 << 7,
        [InspectorName("Varjo Aero, XR-3, VR-3")]
        VarjoAeroXr3Vr3 = 1 << 8,
        [InspectorName("Pimax Droolon Pi 1")]
        PimaxDroolonPi1 = 1 << 9,
        [InspectorName("Pimax Super, Crystal")]
        PimaxSuperCrystal = 1 << 10,
        [InspectorName("Sony PlayStation VR2")]
        Psvr2 = 1 << 11,
        [InspectorName("Samsung Galaxy XR")]
        SamsungGalaxyXr = 1 << 12,
        [InspectorName("HP Reverb G2 Omnicept")]
        HpReverbG2Omnicept = 1 << 13,
        [InspectorName("ARKit (iOS)")]
        ArkitIos = 1 << 14,
        [InspectorName("Android MeowFace")]
        AndroidMeowFace = 1 << 15,
        [InspectorName("EyeTrackVR")]
        EyeTrackVR = 1 << 16,
        [InspectorName("Project Babble")]
        ProjectBabble = 1 << 17,
    }
}
